<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<table class="table text-center w-100">
	<thead>
		<tr>
			<th>순위</th>
			<th>경로</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>광화문</td>
		</tr>
		<tr>
			<td>2</td>
			<td>recommand2</td>
		</tr>
		<tr>
			<td>3</td>
			<td>recommand3</td>
		</tr>
		<tr>
			<td>4</td>
			<td>recommand4</td>
		</tr>
		<tr>
			<td>5</td>
			<td>recommand5</td>
		</tr>
	</tbody>
</table>